##### Aggregate Commerce PRs and Issues into a respective Organizational Project #####

name: Add pull requests and issues to projects

on:
  pull_request

jobs:
  call-workflow-add-to-project:
    uses: dshevtsov/commerce-php/.github/workflows/add-to-project_job.yml@ds_reusable-workflow
    secrets: inherit
