##### Aggregate Commerce PRs and Issues into a respective Organizational Project #####
# Security Note: Uses pull_request_target to allow fork PRs to be added to projects
# This is safe because we only add PRs to projects, no code execution from PRs

name: Add pull requests and issues to projects

on:
  pull_request_target:
    types:
      - opened
  issues:
    types: 
      - opened

# Security: Limit permissions to only what's needed
permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  call-workflow-add-to-project:
    uses: ./.github/workflows/add-to-project_job.yml
    secrets: inherit
