name: Reusable workflow to lint a pull request

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: The git ref to checkout (PR head SHA)

jobs:
    lint-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ inputs.ref }}

            - name: Setup reviewdog
              uses: reviewdog/action-setup@v1.3.0
              with:
                  reviewdog_version: v0.20.3

            - name: Lint Code Base with super-linter and reviewdog
              uses: super-linter/super-linter/slim@v7.3.0
              env:
                  GITHUB_TOKEN: ${{ github.token }}
                  VALIDATE_MARKDOWN: true
                  FIX_MARKDOWN: true
                  MARKDOWN_CONFIG_FILE: .markdownlint.yml
                  VALIDATE_ALL_CODEBASE: false
                  IGNORE_GITIGNORED_FILES: true
                  LOG_LEVEL: DEBUG
                  ACTIONS_RUNNER_DEBUG: true

            - name: Report linting results with reviewdog
              shell: bash
              run: |
                  TMPFILE=$(mktemp)
                  git diff > "${TMPFILE}"
                  if [ ! -s "${TMPFILE}" ]; then
                      echo "No changes detected, skipping reviewdog."
                      exit 0
                  fi
                  git stash --include-untracked
                  reviewdog                        \
                      -f=diff                        \
                      -f.diff.strip=1                \
                      -name="markdownlint-fix"       \
                      -reporter="github-pr-review"   \
                      -filter-mode="diff_context"    \
                      -fail-level=error < "${TMPFILE}"
                  git stash drop || true
              env:
                  REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
