name: Reusable workflow to validate a pull request

on: workflow_call

jobs:
  remark-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Setup Node and Install Dependencies Action
        uses: commerce-docs/devsite-install-action@main
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'yarn.lock'

      - name: Check links
        run: yarn test

  build-test:
    runs-on: ubuntu-latest
    needs: remark-test
    steps:
      - uses: actions/checkout@v4
      - name: Use Setup Node and Install Dependencies Action
        uses: commerce-docs/devsite-install-action@main
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'yarn.lock'

      - name: Build site
        run: yarn build
