name: Call a reusable workflow

on:
  pull_request:
    branches:
      - test

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/wf_test.yml@ds_reusable-workflow
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
